version: '3'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN=flask run --host=0.0.0.0

  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
    ports:
      - "3306:3306"
